name: build

on:

  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - device: m21
    name: "🚧 Build for ${{matrix.device}}"

    steps:
      - name: Checkout source
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 1
          
      - name: Setup Toolchains
        run: |
          sudo apt update
          sudo apt install bison flex libssl-dev libarchive-tools -y
          mkdir -p toolchain
          cd toolchain
          echo 'Download antman and sync'
          bash <(curl -s "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman") -S
          echo 'Patch for glibc'
          bash <(curl -s "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman") --patch=glibc
          echo 'Done'
      
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12
          
      - name: Run build
        run: |
          
          DEVICE=${{matrix.device}} ./build.sh

      - name: Device Name & Config
        run: |
          cat .config | grep CONFIG_LOCALVERSION=
          echo ''
          echo ''
          echo ''
          cat .config

      - name: Upload kernel
        uses: actions/upload-artifact@v3.1.2
        with:
          name: N_kernel-${{matrix.device}}_Clang_18
          path: AIK/N_KERNEL.*.zip
